import type { Metadata } from "next";
import { Roboto_Mono, Lexend_Deca } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Providers } from "@/components/Providers";

const roboto_mono = Roboto_Mono({ subsets: ["latin"], display: "swap" });
export const lexend_deca = Lexend_Deca({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body
            className={cn(
               roboto_mono.className,
               "flex flex-col justify-between gap-8 min-h-screen tracking-tight bg-background text-secondary"
            )}
         >
            <Providers>
               <Header />

               <main className="grow flex flex-col">{children}</main>

               <Footer />
            </Providers>
         </body>
      </html>
   );
}
