import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Providers } from "@/components/Providers";
import { ROBOTO_MONO } from "@/lib/constants";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          ROBOTO_MONO.className,
          "flex flex-col justify-between min-h-screen tracking-tight bg-background text-secondary"
        )}
      >
        <Providers>
          <Header />

          <main className="grow flex flex-col">{children}</main>

          <Footer />
          <Toaster position={"bottom-center"} richColors={true} />
        </Providers>
      </body>
    </html>
  );
}
